name: BlackJack
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: JR <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  RenderingLib:
        git: git://github.com/FarragoFiction/RenderingLib.git



